#!/bin/bash

input_list=$1

line_count=0
while read -r line; do
	line_count=$(( line_count + 1 ))
	file1=`awk -F',' '{print $1}' <<< $line`
	file2=`awk -F',' '{print $2}' <<< $line`

	if [[ "${file1##*.}" != "${file2##*.}" ]]; then
		echo $line on $line_count NOT THE SAME
	fi
done < $input_list

