#!/bin/bash
# Fun with compression

if [[ $(file -b $1) =~ JPEG ]]
then
	echo "IS JPEG"
else
	echo "IS NOT JPEG"
	exit 1
fi

if [[ $2 == "r" ]]
then
	echo "yes"
elif [[ $2 == "i" ]]
then
	echo "still yes"
else
	echo "wrong input"
fi
