#!/bin/bash
# Change "-" to "_" in filenames from list
# Script for Git Bash for Windows

# Input list of files in directory that need to be changed
master_list=$1

function rename_files {
	path=$1
	current_name=$2
	new_name=`echo $current_name | sed 's/-/_/g'`
	mv $path/$current_name $path/$new_name
	echo $new_name
}

function fix_links {
	current_name=$1
	echo current_name in fix_links = $current_name
	new_name=$2
	echo new name in fix_links = $new_name
	grep -rl --exclude-dir=.git "$current_name" . | sed -E 's/^\.\///g' | while read -r line; do
		echo the line is $line
		sed -i'' "s/$current_name/$new_name/g" $line
	done
}

function main {
	while read -r line; do
		clean_line=`echo $line | sed -E 's/^\.\///g'`
		path=`dirname $clean_line`
		current_name=`basename $clean_line`
		fix_links $current_name `rename_files $path $current_name`
	done < $master_list
}

main
