#!/bin/bash
# This will 'git' the status of files containing keyword arguments.

args=("$@")
cmd=""

for (( i = 0; i < $#; i+=1 )); do
	cmd+=" *${args[$i]}*"
done

git status $cmd

read -p "(a) Add these files (c) RESET and commit just these files (q) quit: " choice

if [[ $choice == a ]]
then
	git add $cmd
	git status 
elif [[ $choice == c ]]
then
	git reset HEAD
	git add $cmd
	git commit
elif [[ $choice == q ]]
then
	echo "Done"
else
	cat<< END
	Wrong input...
	Please try again.
END
fi
