#!/bin/bash
# This will 'git' the status of files containing keyword arguments.

args=("$@")
cmd=""

for (( i = 0; i < $#; i+=1 )); do
	cmd+=" *${args[$i]}*"
done

mods_exist=$(git status --porcelain $cmd)

if [[ $mods_exist == "" ]]
then
	echo "Could not find any modified or new files with the specified keywords."
	exit 0
else
	git status $cmd
fi

read -p "(a) Add these files (c) RESET and commit just these files (q) quit: " choice

if [[ $choice == a ]]
then
	git add $cmd
	git status 
elif [[ $choice == c ]]
then
	git reset HEAD
	git add $cmd
	git commit
elif [[ $choice == q ]]
then
	exit 0
else
	cat<< END
	Wrong input...
	Please try again.
END
fi
