#!/bin/bash
# This is a useful git graph view. Using this instead of an alias because
# having much at all in the `.bash_profile` seems to slow down git bash.
git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all
