#!/bin/bash

# Goal is to rename an image file and possibly an associated props file
# and update links to the image.

# Input current name and new desired name WITH extension
input_current=$1
input_new=$2

# Find current image name w/path
original=`find -iname $input_current`

# Rename the image if there is one find match
if [[ -f $original ]]; then
	new=`echo $original | sed "s/$input_current/$input_new/g"`
	mv $original $new

	# Rename the props file if there is one
	if [[ -f $original.props ]]; then
		mv $original.props $new.props
	fi
else
	echo $input_current may have multiple matches
fi

# Replace the current name w/the new name in links
grep -Irl --exclude-dir={Analyzer,.git,Output,FileSync,Users,Reports,Project} "$input_current" . | sed '/bio.flprj/d' | while read -r file; do
	sed -i.bak "s/$input_current/$input_new/g" "$file"
done
